### PR TITLE
New readme

### PR DESCRIPTION
**Pull request by jonay2000**
This branch improves the main README.md and adds some more in subdirectories.

### CODE REVIEW

**Comment by jonay2000** [comment]
Depends on #45

**Comment by NULLx76** [comment]
Looks nice :+1:

**Comment by jonay2000** [comment]
TODO: 
- [ ] Remove the definition of `LOG_LEVEL` from `kernel/src/klibc/include/klibc.h`
- [ ] Remove the `KERNEL_PARAMS` config parameter from the makefile
- [ ] Test setting `LOG_LEVEL` from the makefile
- [ ] Add a description to the readme in `kernel/src/vm`

**Comment by NULLx76** [comment]
Has been merged manually

**Pull request closed without merging**
